<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>strela</string>
	</array>
	<key>firstLineMatch</key>
	<string>module ([a-zA-z0-9][_a-zA-Z0-9]*)(\.([a-zA-z0-9][_a-zA-Z0-9]*))*</string>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>Strela</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>keyword.other</string>
			<key>match</key>
			<string>\b(module|entry|import|export|require|new|mixin|external)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control</string>
			<key>match</key>
			<string>\b(if|else|while|return|foreach|do|for|in|match|case|check)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language</string>
			<key>match</key>
			<string>\b(true|false|null|this)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(alias|module|class|interface|var|entry|enum)\s+([_a-zA-Z]+[_a-zA-Z0-9]*)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(function)\s+([_a-zA-Z]+[_a-zA-Z0-9]*)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.method</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(function)\s+([_a-zA-Z]+[_a-zA-Z0-9]*)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
		</dict>
		<dict>
			<key>name</key>
			<string>support.type</string>
			<key>match</key>
			<string>\b(void|bool|i8|i16|i32|i64|u8|u16|u32|u64|f32|f64)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function</string>
			<key>match</key>
			<string>\b([_a-zA-Z]+[_a-zA-Z0-9]*)\s*\(\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>variable.language</string>
			<key>match</key>
			<string>\b(this)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
					<key>match</key>
					<string>\\.</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<dict>
			<key>name</key>
			<string>comment.line.double-slash</string>
			<key>match</key>
			<string>//.*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.numeric</string>
			<key>match</key>
			<string>\b\d+(\.\d+)?(d|f)?\b</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.strela</string>
	<key>uuid</key>
	<string>344154E7-98D2-4CF9-B86B-D3FAAC53EF80</string>
</dict>
</plist>
